package com.liftlife.liftlife.trainingModule.trainingPlan;

import com.liftlife.liftlife.util.database.FirestoreEntity;
import lombok.*;

/*
POJO class representing whole training plan assigned to client by his coach.
Contains every data needed for client's UI, that he doesn't generate
(data generated by client such as sessions done by him etc. won't
be contained inside of this class).
 */
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@ToString
public class TrainingPlan extends FirestoreEntity {
    private String name;
    private String clientId;
    private String coachId;
}
